language: python
sudo: false

matrix:
  include:
    - env: TOXENV=pypy
      python: pypy
    - env: TOXENV=pypy3
      python: pypy3
    - env: TOXENV=py27
      python: "2.7"
    - env: TOXENV=py34
      python: "3.4"
    - env: TOXENV=py35
      python: "3.5"
    - env: TOXENV=py36
      python: "3.6"
    - env: TOXENV=py37
      python: nightly
    - env: TOXENV=flake8
      python: "2.7"
  allow_failures:
    - python: nightly
    - python: pypy3

install:
  - pip install -U setuptools
  - pip install tox codecov

script: tox

after_success: codecov --token=acff82f6-e810-47fb-8117-1d23ed9e3078

notifications:
  irc:
    channels:
      - "irc.freenode.net#pypa-dev"
    use_notice: true
    skip_join: true
