[build-system]
requires = ["setuptools >= 45.2.0"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py37']
extend-exclude = '''
^/src/wheel/vendored/
'''

[tool.isort]
src_paths = ["src"]
profile = "black"
skip_gitignore = true

[tool.flake8]
max-line-length = 88
