name: Python codeqa/test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install flake8
    - name: Run flake8
      run: flake8 src tests

  test:
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15, macos-11, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "pypy-3.7"]
        exclude:
        - os: macos-11
          python-version: "3.8"
        - os: macos-11
          python-version: "3.9"
        - os: macos-11
          python-version: "pypy-3.7"
        - os: windows-latest
          python-version: "3.8"
        - os: windows-latest
          python-version: "3.9"
        - os: windows-latest
          python-version: "pypy-3.7"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install the project
      run: "pip install --no-binary=:all: ."
    - name: Install test dependencies
      run: pip install .[test]
    - name: Test with pytest
      run: python -b -m pytest -W always --cov-report=xml:pytest-cov.xml
    - name: Send coverage data to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: pytest-cov.xml
